#!/bin/bash

##
## delete-filter
##
## Delete a JSON document containing filters
##

## Source env settings
. .env

## Capture parameters
FILTER=$1

## Validate parameters
if [ -z $FILTER ]; then
    echo "Usage: delete-filter [FILTER_NAME]"
    exit 1
fi

## Get the document
curl -X DELETE $URL/$DB/_design/$FILTER
