#!/bin/bash

##
## get-doc
##
## Get a document by key
##

## Source env settings
. .env

## Capture parameters
KEY=$1

## Validate parameters
if [ -z $KEY ]; then
    echo "Usage: get-doc [KEY]"
    exit 1
fi

## Get the document
curl -sX GET $URL/$DB/$KEY
