#!/bin/bash

##
## load-doc
##
## Load a JSON document from a file into the specified database
##
## NOTE: Document key will be derived from the filename by:
##
## - remove path
## - remove .json extension
## - replace periods with colons
##

## Source env settings
. .env

## Capture parameters
DOC=$1

## Validate required parameters
if [ -z $DOC ]; then
    echo "Usage: load-doc [JSON_FILE]"
    exit 1
fi

## Calculate the position of the key to extract
POS=$(($(grep -o "/" <<< "$DOC" | wc -l)+1))

## Compose key from the filename
KEY=`echo $DOC | awk -F.json '{print $1}' | awk -F"/" -v key=$POS '{print $key}' | tr . :`

## Load the document
curl -X PUT $URL/$DB/$KEY -d @$DOC
