#!/bin/bash

##
## load-security
##
## Load a _security JSON document from a file into a CouchDB database
##

## Source env settings
. .env

## Capture parameters
JSON_FILE=$1

## Validate parameters
if [ -z $DOC ]; then
    echo "Usage: load-security [JSON_FILE]"
    exit 1
fi

## Load the document containing all view definitions

curl -s -X PUT $URL/$COUCHDB_DATABASE/_security -d @$JSON_FILE
